services:
  edge:
    image: quay.io/frrouting/frr:10.2.1
    hostname: edge
    cap_add: [NET_ADMIN, NET_RAW, SYS_ADMIN]
    volumes:
      - ./lab/frr/edge:/etc/frr
    networks:
      edge_core_a:
        ipv4_address: 172.30.1.1
    command: ["/usr/lib/frr/docker-start"]

  core-a:
    image: quay.io/frrouting/frr:10.2.1
    hostname: core-a
    cap_add: [NET_ADMIN, NET_RAW, SYS_ADMIN]
    volumes:
      - ./lab/frr/core-a:/etc/frr
    networks:
      edge_core_a:
        ipv4_address: 172.30.1.2
      core_a_core_b:
        ipv4_address: 172.30.2.1
      core_a_dc:
        ipv4_address: 172.30.4.1
    command: ["/usr/lib/frr/docker-start"]

  core-b:
    image: quay.io/frrouting/frr:10.2.1
    hostname: core-b
    cap_add: [NET_ADMIN, NET_RAW, SYS_ADMIN]
    volumes:
      - ./lab/frr/core-b:/etc/frr
    networks:
      core_a_core_b:
        ipv4_address: 172.30.2.2
      core_b_dc:
        ipv4_address: 172.30.3.1
    command: ["/usr/lib/frr/docker-start"]

  dc:
    image: quay.io/frrouting/frr:10.2.1
    hostname: dc
    cap_add: [NET_ADMIN, NET_RAW, SYS_ADMIN]
    volumes:
      - ./lab/frr/dc:/etc/frr
    networks:
      core_b_dc:
        ipv4_address: 172.30.3.2
      core_a_dc:
        ipv4_address: 172.30.4.2
    command: ["/usr/lib/frr/docker-start"]

networks:
  edge_core_a:
    ipam: {config: [{subnet: 172.30.1.0/30}]}
  core_a_core_b:
    ipam: {config: [{subnet: 172.30.2.0/30}]}
  core_b_dc:
    ipam: {config: [{subnet: 172.30.3.0/30}]}
  core_a_dc:
    ipam: {config: [{subnet: 172.30.4.0/30}]}
