hostname dc
log stdout
!
interface eth0
 ip address 172.30.3.2/30
interface eth1
 ip address 172.30.4.2/30
!
interface lo
 ip address 10.10.0.1/32
!
router ospf
 ospf router-id 10.255.0.4
 network 172.30.3.0/30 area 0
 network 172.30.4.0/30 area 0
 network 10.10.0.1/32 area 0
!
line vty
