hostname core-b
log stdout
!
interface eth0
 ip address 172.30.2.2/30
interface eth1
 ip address 172.30.3.1/30
interface eth2
 ip address 172.30.5.1/30
!
router ospf
 ospf router-id 10.255.0.3
 network 172.30.2.0/30 area 0
 network 172.30.3.0/30 area 0
!
router bgp 65000
 bgp router-id 10.255.0.3
 address-family ipv4 unicast
  redistribute ospf
 exit-address-family
!
line vty
